name: test

on:
  pull_request:
    types:
      - opened
      - closed
      - reopened
      - synchronize
      - edited
      - labeled
      - unlabeled
      - review_requested
      - review_request_removed
  pull_request_review:
    types:
      - submitted
      - dismissed

# to avoid creating duplicate tasks.
concurrency: ci-${{ github.ref }}

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Self test
        uses: ./
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          ASANA_TOKEN: "${{ secrets.ASANA_TOKEN }}"
